# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{prowly}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rafael Magana"]
  s.date = %q{2011-03-28}
  s.description = %q{The Prowly gem is a simple wrapper to the Prowl API, you can use it to send messages to your iPhone in a Rails or pure Ruby application.}
  s.email = %q{raf.magana@gmail.com}
  s.executables = ["prowly_retrieve_apikey", "prowly"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "CONTRIBUTORS.md",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/prowly",
    "bin/prowly_retrieve_apikey",
    "lib/prowly.rb",
    "lib/prowly/interface.rb",
    "lib/prowly/notification.rb",
    "lib/prowly/response.rb",
    "prowly.gemspec",
    "test/helper.rb",
    "test/test_prowly.rb"
  ]
  s.homepage = %q{http://github.com/rafmagana/prowly}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Ruby interface to Prowl (http://prowl.weks.net/)}
  s.test_files = [
    "test/helper.rb",
    "test/test_prowly.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

